export const UPDATE_SOUNDS = 'settings/UPDATE_SOUNDS';
export const UPDATE_RELEASE_CHANNEL = 'settings/UPDATE_RELEASE_CHANNEL';

export const UPDATE_CONCURRENT_DOWNLOADS =
  'settings/UPDATE_CONCURRENT_DOWNLOADS';

export const UPDATE_MINECRAFT_RESOLUTION =
  'settings/UPDATE_MINECRAFT_RESOLUTION';
export const UPDATE_JAVA_PATH = 'settings/UPDATE_JAVA_PATH';
export const UPDATE_JAVA_LATEST_PATH = 'settings/UPDATE_JAVA_LATEST_PATH';
export const UPDATE_JAVA_MEMORY = 'settings/UPDATE_JAVA_MEMORY';
export const UPDATE_JAVA_ARGUMENTS = 'settings/UPDATE_JAVA_ARGUMENTS';
export const UPDATE_DISCORD_RPC = 'settings/UPDATE_DISCORD_RPC';
export const HIDE_WINDOW_ON_GAME_LAUNCH = 'settings/HIDE_WINDOW_ON_GAME_LAUNCH';
export const UPDATE_POTATO_PC_MODE = 'settings/UPDATE_POTATO_PC_MODE';
export const UPDATE_SHOW_NEWS = 'settings/UPDATE_SHOW_NEWS';
export const UPDATE_CURSE_RELEASE_CHANNEL =
  'settings/UPDATE_CURSE_RELEASE_CHANNEL';
export const UPDATE_INSTANCE_SORT_METHOD =
  'settings/UPDATE_INSTANCE_SORT_METHOD';
export const UPDATE_MC_STARTUP_METHOD = 'UPDATE_MC_STARTUP_METHOD';

export const UPDATE_FULLSCREEN = 'settings/UPDATE_FULLSCREEN';
export const UPDATE_FOV = 'settings/UPDATE_FOV';
export const UPDATE_FPS = 'settings/UPDATE_FPS';
export const UPDATE_RENDER_DISTANCE = 'settings/UPDATE_RENDER_DISTANCE';
export const UPDATE_GUI_SCALE = 'settings/UPDATE_GUI_SCALE';
export const UPDATE_AUTO_JUMP = 'settings/UPDATE_AUTO_JUMP';
export const UPDATE_SOUNDCATEGORY_MASTER =
  'settings/UPDATE_SOUNDCATEGORY_MASTER';
export const UPDATE_SOUNDCATEGORY_MUSIC = 'settings/UPDATE_SOUNDCATEGORY_MUSIC';
export const UPDATE_SOUNDCATEGORY_JUKEBOX =
  'settings/UPDATE_SOUNDCATEGORY_JUKEBOX';
export const UPDATE_SOUNDCATEGORY_WEATHER =
  'settings/UPDATE_SOUNDCATEGORY_WEATHER';
export const UPDATE_SOUNDCATEGORY_BLOCKS =
  'settings/UPDATE_SOUNDCATEGORY_BLOCKS';
export const UPDATE_SOUNDCATEGORY_HOSTILE =
  'settings/UPDATE_SOUNDCATEGORY_HOSTILE';
export const UPDATE_SOUNDCATEGORY_NEUTRAL =
  'settings/UPDATE_SOUNDCATEGORY_NEUTRAL';
export const UPDATE_SOUNDCATEGORY_PLAYER =
  'settings/UPDATE_SOUNDCATEGORY_PLAYER';
export const UPDATE_SOUNDCATEGORY_AMBIENT =
  'settings/UPDATE_SOUNDCATEGORY_AMBIENT';
export const UPDATE_SOUNDCATEGORY_VOICE = 'settings/UPDATE_SOUNDCATEGORY_VOICE';
export const UPDATE_VSYNC = 'settings/UPDATE_VSYNC';
export const UPDATE_MUTE_ALL_SOUNDS = 'settings/UPDATE_MUTE_ALL_SOUNDS';
